Models/Response.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Practice.Models
{
    public class Response
    {
        [Display(Name = "Response Id")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ResponseId { get; set; }

        [Display(Name = "First Name")]
        [Required()]
        [MinLength(2)]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required()]
        [MinLength(2)]
        public string LastName { get; set; }

        [Display(Name = "Email")]
        [Required()]
        [EmailAddress()]
        public string Email { get; set; }

        [Display(Name = "Phone Number")]
        [Required()]
        [Phone()]
        public string PhoneNumber { get; set; }

        [Display(Name = "Checked")]
        public Boolean Checked { get; set; }

        [Display(Name = "User Id")]
        public int? UserId { get; set; }
        [Display(Name = "Project Id")]
        public int ProjectId { get; set; }

        public  User User { get; set; }
        public  Project Project { get; set; }
    }
}

Controllers/ResponseController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Practice.Models;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Diagnostics;

namespace Practice.Controllers
{
    public class ResponseController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: Response
        public ActionResult Index()
        {
            ViewBag.projects = new SelectList(db.Project, "ProjectId", "Name");
            return View(db.Response.Include(r => r.Project).Include(r => r.User).ToList());
        }

        // GET: Response/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Response response = db.Response.Find(id);
            if (response == null)
            {
                return HttpNotFound();
            }
            return PartialView("Details", response);
        }

        // GET: Response/Create
        public ActionResult Create(int? id)
        {
            List<string> projects = new List<string> ();

            foreach (var row in db.Project)
            {
                projects.Add(row.Name);
            }

            ViewBag.Projects = projects;
            ViewBag.Selected = (db.Project.Find(id).Name != null) ? db.Project.Find(id).Name : null;

            return PartialView("Create");
        }

        // POST: Response/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public string Create([Bind(Include = "FirstName,LastName,Email,PhoneNumber")] Response response, string Name)
        {
            var project = db.Project.Where(r => r.Name == Name);
            System.Diagnostics.Debug.WriteLine(Name);
            if (ModelState.IsValid && project.Count() == 1)
            {
                try
                {
                    var user = db.User.Where(r => r.FirstName == response.FirstName && r.LastName == response.LastName);
                    response.UserId = user.First().UserId;
                }
                catch (InvalidOperationException e)
                {
                    Debug.WriteLine("Response is a new user or has no matching user in database:" + e);
                }
               
                response.ProjectId = project.First().ProjectId;
                response.Checked = false;
                db.Response.Add(response);
                db.SaveChanges();

            }
            var lastAddedResponse = db.Response.Where(r => r.FirstName == response.FirstName && r.LastName == response.LastName && r.Project.Name == Name);
            return JsonConvert.SerializeObject(lastAddedResponse, new JsonSerializerSettings { PreserveReferencesHandling = PreserveReferencesHandling.Objects });
        }

        // GET: Response/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Response response = db.Response.Find(id);
            if (response == null)
            {
                return HttpNotFound();
            }

            List<string> projects = new List<string>();

            foreach(Project row in db.Project)
            {
                projects.Add(row.Name);
            }

            ViewBag.Projects = projects;
            if (response.Project.Name != null)
                ViewBag.Current = response.Project.Name;
            return PartialView("Edit", response);
        }

        // POST: Response/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public string Edit([Bind(Include = "ResponseId,FirstName,LastName,Email,PhoneNumber,Checked,UserId")] Response response, string name)
        {
            var project = db.Project.Where(r => r.Name == name);
            if (ModelState.IsValid && project.Count() == 1)
            {
                response.ProjectId = project.First().ProjectId;
                db.Entry(response).State = EntityState.Modified;
                db.SaveChanges();
            }
            return JsonConvert.SerializeObject(db.Response.Where(r => r.ResponseId == response.ResponseId), Formatting.Indented, new JsonSerializerSettings { PreserveReferencesHandling = PreserveReferencesHandling.Objects });
        }

        // GET: Response/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Response response = db.Response.Find(id);
            if (response == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete", response);
        }

        // POST: Response/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public int DeleteConfirmed(int id)
        {
            Response response = db.Response.Find(id);
            db.Response.Remove(response);

            return db.SaveChanges();
        }

        [HttpPost]
        public ActionResult Check(int? id)
        {
            if (id != null)
            {
                Response response = db.Response.Find(id);
                if (response != null)
                {
                    response.Checked = !response.Checked;
                    db.SaveChanges();
                }
                else
                {
                    return HttpNotFound();
                }
                return Json (new { check = response.Checked } );
            }
            return null;
        }

        [HttpGet]
        public Response getResponse(int? id)
        {
            return db.Response.Find(id);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Response/Create.cshtml
@model Practice.Models.Response
@{
    ViewBag.Title = "Create";
    List<string> projects = ViewBag.Projects;
    string selected = ViewBag.Selected;
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <script>
        $(function () {
            $(document).tooltip({
                position: {
                    my: "left top",
                    at: "right+5 top-5",
                    collision: "none"
                }
            });
        });
    </script>
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Name", "Project Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Name", new SelectList(projects, selected), "Select Project", new { @class = "drop form-input", @id = "projectName" } )
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, "First Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control  form-input", @id = "firstName" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, "Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control form-input", @id = "lastName" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control form-input", @id = "email" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, "Phone Number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control form-input", @id = "phoneNumber" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div id="submit" style="display: none;">
            <p>Your response has been submited!</p>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Response/Delete.cshtml
@model Practice.Models.Response

@{
    ViewBag.Title = "Delete";
}

<h3>Are you sure you want to delete this response?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ResponseId)
        </dt>

        <dd>
            <span id="responseId">
                @Html.DisplayFor(model => model.ResponseId)
            </span>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @{
                if (Model.UserId == null || Model.UserId.HasValue == false)
                {
                    @Html.DisplayName("New")
                }
                else
                {
                    @Html.DisplayFor(model => model.UserId)
                }
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Checked)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Checked)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
    }
</div>

Views/Response/Details.cshtml
@model Practice.Models.Response

@{
    ViewBag.Title = "Details";
}

<div id="content">
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Checked)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Checked)
        </dd>

    </dl>
</div>
@*<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ResponseId }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

Views/Response/Edit.cshtml
@model Practice.Models.Response

@{
    ViewBag.Title = "Edit";
    List<string> projects = ViewBag.Projects;
    string selected = ViewBag.Current;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.ResponseId, htmlAttributes: new { @id = "responseId" })
        @Html.HiddenFor(model => model.UserId, htmlAttributes: new { @id = "userId" })

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", @id = "firstName" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", @id = "lastName" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @id = "email" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control", @id = "phoneNumber" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Checked, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Checked, new { htmlAttributes = new { @id = "checked" } })
                    @Html.ValidationMessageFor(model => model.Checked, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Name", "Project Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Name", new SelectList(projects, selected), "Select Project", new { @id = "projectName" } )
            </div>
        </div>
        
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Response/Index.cshtml
@model IEnumerable<Practice.Models.Response> 

@{
    ViewBag.Title = "Responses";
}

<h2>Responses</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ResponseId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Project.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Checked)
        </th>
        <th></th>
    </tr>
@foreach (var item in Model)
{
    <tr>
        <td id="responseId">
               @Html.DisplayFor(modelItem => item.ResponseId)
        </td>
        <td id="id">
            @{
                if (item.UserId == null || item.UserId.HasValue == false)
                {
                    @Html.DisplayName("New")
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.UserId)
                }
            }
        </td>
        <td id="project">
            @Html.DisplayFor(modelItem => item.Project.Name)
        </td>
        <td id="firstName">
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td id="lastName">
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td id="email">
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td id="phoneNumber">
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td id="check">
            @Html.DisplayFor(modelItem => item.Checked)
        </td>
        <td>
            <a href="" , class="checkButton">Check</a> |
            <a onclick="ajaxCRUD($(this).parent().parent(), 'Response', 'Edit')" href="#", class="editButton">Edit</a> |
            <a onclick="details($(this).parent().parent(), 'Response')" href="#" , class="detailsButton">Details</a> |
            <a onclick="ajaxCRUD($(this).parent().parent(), 'Response', 'Delete')" href="#" , class="detailsButton">Delete</a> |
        </td>
    </tr>
}
</table>

<script type="text/javascript">
    //toggles the checked parameter for responses so we know if a response has been seen and written down
    $(".checkButton").click(function() {
            event.preventDefault();
            var row = $(this).parent().parent();
            $.ajax({
                url: '@Url.Action("Check", "Response")',
                type: "POST",
                data: { "id": $(this).parent().parent().find("#responseId").html() },
                success: function (result) {
                    if (result.check == true) {
                        row.find("#check").replaceWith("<td id='check'><input checked='checked' class='check-box' disabled='disabled' type='checkbox'></td>");
                    } 
                    else {
                        row.find("#check").replaceWith("<td id='check'><input class='check-box' disabled='disabled' type='checkbox'></td>");
                    }
                }
            });
    });
</script>